name: CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          manifest-path: pyproject.toml
          run-install: false
      - name: Run code formatting checks
        run: pixi run lint-manual
